# 기준 봉 크기
candle_duration = 30 #단위는 min
#매수 조건
#case1
[buy]
  [buy.condition]
    [buy.condition.case1]
      prev_candle_count = 3  #(이전 {3}개 봉
      prev_volume_surge_ratio = 3 # 이전 봉들의 평균거래량 * {x} 배
      prev_price_surge_ratio = 1.01 #1-3. 이전 {3}개봉의 평균가격(각 봉의(open+close)/2의 평균)보다 {1%}이상 상승)
    [buy.condition.case2]
      prev_candle_count = 3  #(이전 {3}개 봉
      prev_volume_surge_ratio2 = 5 # 이전 봉들의 평균거래량 * {x} 배
      prev_max_num_candle = 10 #2-3. 이전 {10}개봉의 최고가격

#매도 조건
[sell]
  [sell.condition]
    target_profit = 0.05 # 5% 이상이면 바로 매도
    [sell.condition.case1]
      rate_ratio_from_low = 0.4 # 현재가가 저점
