# 30분봉이 기준
candle_duration = 30 #30분 봉 기준,감시기준 봉

# case1 에서 30분 봉이 최소 3번 지난 이 후 부터 매수 조건이 충족된다.
waiting = 90

#매수 조건
#case1
[buy]
  [buy.condition]
    [buy.condition.case1]
      prev_candle_count = 3  #(이전 {3}개 봉
      prev_volume_surge_ratio = 3 # 이전 봉들의 평균거래량 * {x} 배
      prev_price_surge_ratio = 1.01 #1-3. 이전 {3}개봉의 평균가격(각 봉의(open+close)/2의 평균)보다 {1%}이상 상승)
    [buy.condition.case2]
      prev_candle_count = 3  #(이전 {3}개 봉
      prev_volume_surge_ratio = 5 # 이전 봉들의 평균거래량 * {x} 배
      prev_max_num_candle = 10 #2-3. 이전 {10}개봉의 최고가격